"""journal2

Revision ID: 3c0d73201a7d
Revises: a1b38aa1d33f
Create Date: 2026-03-29 05:36:15.728716
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c0d73201a7d'
down_revision = 'a1b38aa1d33f'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_journal_insights_journal_entry_id', table_name='journal_insights')
    op.drop_table('journal_insights')
    op.drop_index('ix_journal_micro_actions_journal_entry_id', table_name='journal_micro_actions')
    op.drop_table('journal_micro_actions')
    op.add_column('daily_journal_entries', sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('daily_journal_entries', sa.Column('micro_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_journal_entries', 'micro_actions')
    op.drop_column('daily_journal_entries', 'insights')
    op.create_table('journal_micro_actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('journal_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('due_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['daily_journal_entries.id'], name='journal_micro_actions_journal_entry_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='journal_micro_actions_pkey')
    )
    op.create_index('ix_journal_micro_actions_journal_entry_id', 'journal_micro_actions', ['journal_entry_id'], unique=False)
    op.create_table('journal_insights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('journal_entry_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['daily_journal_entries.id'], name='journal_insights_journal_entry_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='journal_insights_pkey')
    )
    op.create_index('ix_journal_insights_journal_entry_id', 'journal_insights', ['journal_entry_id'], unique=False)
    # ### end Alembic commands ###
