"""add user profile

Revision ID: 86f40a192f8b
Revises: 
Create Date: 2026-03-29 00:57:58.328592
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f40a192f8b'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_sub', sa.String(length=255), nullable=False))
    op.drop_index('ix_users_device_id', table_name='users')
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.drop_column('users', 'device_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.create_index('ix_users_device_id', 'users', ['device_id'], unique=True)
    op.drop_column('users', 'google_sub')
    # ### end Alembic commands ###
