"""journal

Revision ID: a1b38aa1d33f
Revises: 86f40a192f8b
Create Date: 2026-03-29 04:57:56.255590
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b38aa1d33f'
down_revision = '86f40a192f8b'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reflections_user_id', table_name='reflections')
    op.drop_table('reflections')
    op.drop_index('ix_daily_questions_date', table_name='daily_questions')
    op.drop_table('daily_questions')
    op.drop_index('ix_micro_actions_user_id', table_name='micro_actions')
    op.drop_table('micro_actions')
    op.drop_index('ix_weekly_summaries_user_id', table_name='weekly_summaries')
    op.drop_table('weekly_summaries')
    op.drop_index('ix_pattern_insights_user_id', table_name='pattern_insights')
    op.drop_table('pattern_insights')
    op.drop_column('daily_journal_entries', 'mood')
    op.add_column('generated_questions', sa.Column('question_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('generated_questions', 'schema')
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.alter_column('users', 'google_sub',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('users', 'google_sub',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    op.add_column('generated_questions', sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('generated_questions', 'question_schema')
    op.add_column('daily_journal_entries', sa.Column('mood', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_table('pattern_insights',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pattern_insights_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pattern_insights_pkey')
    )
    op.create_index('ix_pattern_insights_user_id', 'pattern_insights', ['user_id'], unique=False)
    op.create_table('weekly_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('week_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('shared_with_peer', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='weekly_summaries_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='weekly_summaries_pkey')
    )
    op.create_index('ix_weekly_summaries_user_id', 'weekly_summaries', ['user_id'], unique=False)
    op.create_table('micro_actions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('due_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='micro_actions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='micro_actions_pkey')
    )
    op.create_index('ix_micro_actions_user_id', 'micro_actions', ['user_id'], unique=False)
    op.create_table('daily_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('generated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='daily_questions_pkey')
    )
    op.create_index('ix_daily_questions_date', 'daily_questions', ['date'], unique=False)
    op.create_table('reflections',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('mood_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reflections_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reflections_pkey')
    )
    op.create_index('ix_reflections_user_id', 'reflections', ['user_id'], unique=False)
    # ### end Alembic commands ###
